Site/Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Models
{
    public class Categoria
    {
        public virtual ICollection<Prato> prato { get; set; }
        public virtual ICollection<Restaurante> restaurante { get; set; }
    }
}

Site/Models/Prato.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Models
{
    public class Prato
    {
        public int idP { get; set; }
        public int idR { get; set; }
        public string prato { get; set; }
        public float preco { get; set; }

    }
}

Site/Models/Restaurante.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Site.Models
{
    public class Restaurante
    {
        public int idR { get; set; }
        public string nome { get; set; }
    }
}

Site/Controllers/DadosController.cs
using Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site.Controllers
{
    public class DadosController : Controller
    {
        public ActionResult IndexP()
        {
            var p = new AplicacaoP();
            var listaPratos = p.Select();
            return View(listaPratos);
        }       


        public ActionResult CadastrarP()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CadastrarP(Prato p)
        {
                var prato = new AplicacaoP();
                prato.Insert(p);
                return RedirectToAction("IndexP");
        }


        public ActionResult EditarP(int id)
        {
            var p = new AplicacaoP();
            var prato=p.ListaId(id);
            return View(prato);
        }
        [HttpPost]
        public ActionResult EditarP(Prato p)
        {
                var prato = new AplicacaoP();
                prato.Update(p);
                return RedirectToAction("IndexP");
        }


        public ActionResult ExcluirP(int id)
        {
            var r = new AplicacaoP();
            var restaurante = r.ListaId(id);
            return View(restaurante);
        }
        [HttpPost, ActionName("ExcluirP")]
        public ActionResult ExcluirConfirmar(Prato p)
        {
            var prato = new AplicacaoP();
            prato.Delete(p);
            return RedirectToAction("IndexP");
        }

    }
}

Site/Controllers/HomeController.cs
using Site.Models;
using System.Web.Mvc;

namespace Site.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Site/Controllers/RestauranteController.cs
using Site.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Site.Controllers
{
    public class RestauranteController : Controller
    {
        public ActionResult IndexR()
        {
            var r = new AplicacaoR();
            var listaRestaurantes = r.Select();
            return View(listaRestaurantes);
        }

        public ActionResult CadastrarR()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CadastrarR(Restaurante r)
        {
                var restaurante = new AplicacaoR();
                restaurante.Insert(r);
                return RedirectToAction("IndexR");
        }

        public ActionResult EditarR(int id)
        {
            var r = new AplicacaoR();
            var restaurante = r.ListaId(id);
            if (r == null)
            {
                return HttpNotFound();
            }
            return View(restaurante);
        }

        [HttpPost]
        public ActionResult EditarR(Restaurante r)
        {
                var restaurante = new AplicacaoR();
                restaurante.Update(r);
                return RedirectToAction("IndexR");
        }


        public ActionResult ExcluirR(int id)
        {
            var r = new AplicacaoR();
            var restaurante = r.ListaId(id);    
            return View(restaurante);
        }

        [HttpPost, ActionName("ExcluirR")]
        public ActionResult ExcluirConfirmar(Restaurante r)
        {
            var restaurante = new AplicacaoR();
            restaurante.Delete(r);
           return RedirectToAction("IndexR");
        }
    }
}

Site/Views/Dados/CadastrarP.cshtml
@model Site.Models.Prato

@{
    ViewBag.Title = "CadastrarP";
}

<h2>Cadastro de Pratos</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Restaurante Pertencente</b>
            </div>

            <div class="col-md-10">
                @Html.EditorFor(model => model.idR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idR, "", new { @class = "text-danger" })

            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Nome do Prato</b>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.prato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class = "control-label col-md-2">
                <b>Preço do Prato</b>
            </div>

            <div class="col-md-10">
                @Html.EditorFor(model => model.preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "IndexP")
</div>

Site/Views/Dados/EditarP.cshtml
@model Site.Models.Prato

@{
    ViewBag.Title = "EditarP";
}

<h2>EditarP</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Prato</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prato, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prato, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prato, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.preco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.preco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.preco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexP")
</div>

Site/Views/Dados/ExcluirP.cshtml
@model Site.Models.Prato

@{
    ViewBag.Title = "ExcluirP";
}

<h2>ExcluirP</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Prato</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Codigo: ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idP)
        </dd>

        <dt>
            @Html.DisplayName("Restaurante: ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idR)
        </dd>

        <dt>
            @Html.DisplayName("Nome: ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.prato)
        </dd>

        <dt>
            @Html.DisplayName("Preço: ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.preco)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "IndexP")
        </div>
    }
</div>

Site/Views/Dados/IndexP.cshtml
@model IEnumerable<Site.Models.Prato>

@{
    ViewBag.Title = "IndexP";
}

<h2>IndexP</h2>

<p>
    @Html.ActionLink("Cadastrar Novo", "CadastrarP")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idP)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prato)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.preco)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.idP)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.idR)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.prato)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.preco)
        </td>
        <td>
            @Html.ActionLink("Editar", "EditarP", new { id=item.idP }) |
            @Html.ActionLink("Excluir", "ExcluirP", new {id = item.idP })
        </td>
    </tr>
}

</table>

Site/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<div class="slider">
    <ul>
        <li> <img src="~/imagem/prato1.jpg" width="800" height="400"> </li>
        <li> <img src="~/imagem/prato2.jpg" width="800" height="400"> </li>
        <li> <img src="~/imagem/prato3.jpg" width="800" height="400"> </li>
        <li> <img src="~/imagem/prato4.jpg" width="800" height="400"> </li>
    </ul>
</div><!--Fim Slider-->

<h2>Sitema de Cadastro de Restaurantes</h2> 

Site/Views/Restaurante/CadastrarR.cshtml
@model Site.Models.Restaurante

@{
    ViewBag.Title = "CadastrarR";
}

<h2>Cadastro de Restaurantes</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <div class="control-label col-md-2">
                <b>Nome do Restaurante</b>
            </div>

            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "IndexR")
</div>

Site/Views/Restaurante/EditarR.cshtml
@model Site.Models.Restaurante

@{
    ViewBag.Title = "EditarR";
}

<h2>EditarR</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Restaurante</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idR, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idR, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idR, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "IndexR")
</div>

Site/Views/Restaurante/ExcluirR.cshtml
@model Site.Models.Restaurante

@{
    ViewBag.Title = "ExcluirR";
}

<h2>Excluir Restaurante</h2>

<h4>Deseja realmente excluir o seguinte restaurante?</h4>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Codigo: ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idR)
        </dd>
        
        <dt>
            @Html.DisplayName("Nome: ")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nome)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "IndexR")
        </div>
    }
</div>

Site/Views/Restaurante/IndexR.cshtml
@model IEnumerable<Site.Models.Restaurante>

@{
    ViewBag.Title = "IndexR";
}

<h2>IndexR</h2>

<p>
    @Html.ActionLink("Cadastrar Novo", "CadastrarR")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.idR)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nome)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.idR)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.nome)
        </td>
        <td>
            @Html.ActionLink("Editar", "EditarR", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Excluir", "ExcluirR", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

Site/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    
</head>
<body>
    <div id="menu">
        <ul>
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li>@Html.ActionLink("Restaurantes", "IndexR", "Restaurante")</li>
            <li>@Html.ActionLink("Pratos", "IndexP", "Dados")</li>
        </ul>
    </div><!--Fim MENU-->

     <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Rede de Restaurantes", "Inicial", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - daniel-costa@ufu.br</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>